const colleges = [
  {
    id: "1",
    title: "GL Bajaj Institute of Technology & Management",
    location: "Greater Noida",
    university: "AKTU Lucknow",
    imgLink: "https://lh3.googleusercontent.com/d/1rPG2wvu7WH6Lmbw304OQc1H66iy8QDux",
    established: "2005",
    area: 30.0,
    naacGrade: "A+",
    description: "GL Bajaj Institute of Technology and Management, a jewel of the Rajeev Memorial Academic Welfare Society, firmly established itself as a leading educational institution in the vibrant Greater Noida/Delhi-NCR region. With AICTE approval and affiliation to Dr. A.P.J. Abdul Kalam Technical University, it offers sought after programs like B.Tech, MBA, and MCA. What truly sets GL Bajaj apart is its dedication to holistic learning , cultivating academic excellence alongside personal growth. As a self financed institute, it has proudly held the highest pass percentage in the Noida and Greater Noida region for eight consecutive years. The institute's consistent top ranks in AKTU results, coupled with accolades from NIRF and other recognitions, underscore its commitment to nurturing future leaders. GL Bajaj isn\u2019t just a place to study; it\u2019s where ambitions take flight and bright futures are shaped, making it a standout name in engineering and management education.",
    mapLink: "https://www.google.com/maps/place/GL+Bajaj+Institute+of+Technology+%26+Management/@28.4717761,77.4868976,17z/data=!4m10!1m2!2m1!1sgl+bajaj!3m6!1s0x390ceb193588358f:0x8274cec5a1321578!8m2!3d28.4722284!4d77.4889615!15sCghnbCBiYWphaloKIghnbCBiYWphapIBEmVuZ2luZWVyaW5nX3NjaG9vbOABAA!16s%2Fg%2F11ghrkc0zw?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoASAFQAw%3D%3D",
    address: "Plot No. 2, APJ Abdul Kalam Rd, Knowledge Park III, Greater Noida, Uttar Pradesh 201306"
  },
  {
    id: "2",
    title: "Galgotias College of Engineering & Technology (GCET)",
    location: "Greater Noida",
    university: "AKTU Lucknow",
    imgLink: "https://lh3.googleusercontent.com/d/1vha-XVkX4OUycXeJHqWvGxVo0BtY1h42",
    established: "2000",
    area: 19.0,
    naacGrade: "A+",
    description: "Galgotias College of Engineering & Technology (GCET), part of Galgotias Educational Institutions founded by the Shakuntla Educational and Welfare Society, is a leading institute for technical and management education. Under the visionary leadership of Chairman Mr. Suneel Galgotia, GCET has been shaping careers since 2000. Approved by AICTE and affiliated with Dr. A.P.J. Abdul Kalam Technical University, the institution is renowned for combining theoretical knowledge with practical skills to develop capable professionals. It offers programs like B.tech, M.tech and MBA .Situated on a sprawling 19 acre campus along the expressway connecting Greater Noida to New Delhi, GCET provides a vibrant learning environment. The campus boasts state of the art facilities, secure hostels, seminar halls, and sports amenities, creating a self-sustaining ecosystem. Recognized both nationally and internationally, GCET has built a reputation for academic excellence, innovation, and fostering holistic growth, making it a trusted name in quality education.",
    mapLink: "https://www.google.co.in/maps/place/GALGOTIAS+COLLEGE+OF+ENGINEERING+AND+TECHNOLOGY,+Knowledge+Park+II,+Greater+Noida,+Uttar+Pradesh+201310/@28.4571329,77.4978,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipOZkK7rBOx6FIOUou7jDAbJkPRKraJVk4F6aa4m!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipOZkK7rBOx6FIOUou7jDAbJkPRKraJVk4F6aa4m%3Dw114-h86-k-no!7i8160!8i6144!4m7!3m6!1s0x390cc1dc8b29c0e1:0x4ee84fe65c694f0!8m2!3d28.4571329!4d77.4978!10e5!16s%2Fg%2F11b8txl6pk?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "Knowledge Park II, Greater Noida, Uttar Pradesh 201310"
  },
  {
    id: "3",
    title: "KCC insitute of Technology & Management",
    location: "Greater Noida",
    university: "AKTU Lucknow",
    imgLink: "https://lh3.googleusercontent.com/d/1vZtkaBocB7U0Ee27P-xThZP2e8fvibx7",
    established: "2009",
    area: 40.0,
    naacGrade: "A",
    description: "KCC Institute of Technology and Management (KCC ITM), located in Greater Noida, is a premier educational institution dedicated to excellence in technical and management education. Established under the KCC Group, the institute is affiliated with Dr. A.P.J. Abdul Kalam Technical University and approved by AICTE. Known for its innovative teaching methods and industry aligned curriculum, KCC ITM offers programs like B.Tech, MBA, and MCA, fostering both academic and professional growth. Spread across a sprawling 40 acre campus, KCC ITM provides a vibrant learning environment with state of the art infrastructure, including modern classrooms, well-equipped labs, and secure hostels. The campus also features seminar halls, sports facilities, and recreational spaces, ensuring a holistic student experience. With a strong focus on placements and skill development, KCC ITM has earned recognition as one of the top institutions in the region, preparing students to excel in their careers and contribute meaningfully to society.",
    mapLink: "https://www.google.co.in/maps/place/KCC+Institute+of+Technology+%26+Management/@28.4691239,77.4934117,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipOFRB_RIWTVBEebwLADOtvkuUa1GqqbzQJ4PVmo!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipOFRB_RIWTVBEebwLADOtvkuUa1GqqbzQJ4PVmo%3Dw203-h86-k-no!7i3153!8i1330!4m7!3m6!1s0x390cea74cbe81503:0x3d100ac5d4e327a!8m2!3d28.4694022!4d77.4934384!10e5!16s%2Fg%2F1tgcq7lk?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "2B, 2C, Vashishth Rd, Knowledge Park III, Greater Noida, Uttar Pradesh 201306"
  },
  {
    id: "4",
    title: "Noida Institute of Engineering & Technology (NIET)",
    location: "Greater Noida",
    university: "AKTU Lucknow",
    imgLink: "https://lh3.googleusercontent.com/d/1wPQrBIFYmHKL5PKk08SkJPvdP0zNdRQ5",
    established: "2001",
    area: 14.0,
    naacGrade: "A",
    description: "Noida Institute of Engineering and Technology (NIET), located in Greater Noida, is a prestigious institution dedicated to providing top-notch technical and management education. Established in 2001 under the City Educational and Welfare Society, NIET is affiliated with Dr. A.P.J. Abdul Kalam Technical University and approved by AICTE. The institute is renowned for its innovative teaching methods, industry focused curriculum, and emphasis on research and skill development. Spread across a lush 23 acre campus, NIET offers a vibrant learning environment with modern classrooms, advanced laboratories, and well-equipped libraries. The campus also features secure hostels, seminar halls, sports facilities, and recreational spaces, ensuring a holistic student experience. As the first private institute in Uttar Pradesh to achieve autonomous status, NIET has earned accolades from NAAC, NBA, and NIRF for its academic excellence. With a strong focus on placements and entrepreneurship, NIET continues to shape future-ready professionals and leaders.",
    mapLink: "https://www.google.co.in/maps/place/Noida+Institute+of+Engineering+and+Technology+(NIET,+Greater+Noida)/@28.4629043,77.4906933,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipM-_ozP9yCZybpCPHht8DO1TwuFiFdQwuhDIXDK!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipM-_ozP9yCZybpCPHht8DO1TwuFiFdQwuhDIXDK%3Dw114-h86-k-no!7i4000!8i3000!4m11!1m2!2m1!1sNIET!3m7!1s0x390cc1e055d148a1:0x9f5207f7f0bc8f63!8m2!3d28.4629043!4d77.4906933!10e5!15sCgROSUVUIgOIAQFaBiIEbmlldJIBEmVuZ2luZWVyaW5nX3NjaG9vbOABAA!16s%2Fm%2F06zrd2c?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "19, Institutional Area, Knowledge Park II, Greater Noida, Uttar Pradesh 201306"
  },
  {
    id: "5",
    title: "Greater Noida Institute of Technology (GNIOT)",
    location: "Greater Noida",
    university: "AKTU Lucknow",
    imgLink: "https://lh3.googleusercontent.com/d/1ZUsC1TNkrhyYUsNn3a23xLXBFkgQp9hi",
    established: "2001",
    area: 20.0,
    naacGrade: "A+",
    description: "Greater Noida Institute of Technology (GNIOT), located in the heart of Greater Noida, is a distinguished institution committed to excellence in technical and management education. Established in 2001 under the umbrella of the Shri Ram Educational Trust, GNIOT is affiliated with Dr. A.P.J. Abdul Kalam Technical University and approved by AICTE. The institute is known for its industry oriented curriculum, innovative teaching methods, and focus on research and skill development. Spread across a sprawling campus, GNIOT offers a dynamic learning environment with state of the art infrastructure, including modern classrooms, advanced laboratories, and a well stocked library. The campus also features secure hostels, seminar halls, sports facilities, and recreational spaces, ensuring a well rounded student experience. With a strong emphasis on placements and entrepreneurship, GNIOT has earned recognition as one of the top institutions in the region, shaping future ready professionals and leaders in engineering and management.",
    mapLink: "https://www.google.co.in/maps/place/GNIOT+Group+of+Institutions/@28.4606919,77.4954681,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipMr2iiTxZkwB3-2iJ-hTiZn0qpeRQ0D5jH0PuYn!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipMr2iiTxZkwB3-2iJ-hTiZn0qpeRQ0D5jH0PuYn%3Dw86-h114-k-no!7i3024!8i4032!4m7!3m6!1s0x390cc1ddc0000001:0xfc29bf57c9c17cf1!8m2!3d28.4613478!4d77.4958983!10e5!16s%2Fm%2F0zdkrkw?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "Plot No. 7, Knowledge Park II, Greater Noida, Uttar Pradesh 201310"
  },
  {
    id: "6",
    title: "LLOYD Group of Institutions",
    location: "Greater Noida",
    university: "AKTU Lucknow",
    imgLink: "https://lh3.googleusercontent.com/d/15z2HrNn_J8-QPF5e_fC5OiB3exqcDHTF",
    established: "2004",
    area: 25.0,
    naacGrade: "B+",
    description: "Lloyd Group of Institutions, situated in Greater Noida, is a renowned educational hub offering excellence in diverse fields such as engineering, management, law, and pharmacy. Established under the visionary leadership of its founders, the institution is affiliated with Dr. A.P.J. Abdul Kalam Technical University and approved by AICTE. It offers a wide range of industry oriented courses ranging from Engineering to Management . Lloyd is celebrated for its industry integrated curriculum, innovative teaching methods, and commitment to producing skilled professionals. Spread across a modern campus, Lloyd provides a vibrant learning environment with state of the art infrastructure, including advanced classrooms, well-equipped labs, and a comprehensive library. The campus also features secure hostels, seminar halls, sports facilities, and recreational spaces, ensuring a holistic student experience. Recognized for its academic excellence and strong placement record, Lloyd Group of Institutions has earned a reputation as a trusted name in higher education, preparing students to excel in their careers and contribute meaningfully to society.",
    mapLink: "https://www.google.co.in/maps/place/Lloyd+Institute+of+Engineering+%26+Technology/@28.4575225,77.4927599,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipO43otpfBpBDCxGicZinsU_SfIGEZYSZSs_27wT!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipO43otpfBpBDCxGicZinsU_SfIGEZYSZSs_27wT%3Dw129-h86-k-no!7i4256!8i2832!4m11!1m2!2m1!1slloyd+group+of+institutions!3m7!1s0x390cc117b9edb9ef:0xdab6d36968d2fd8b!8m2!3d28.4572102!4d77.4929512!10e5!15sChtsbG95ZCBncm91cCBvZiBpbnN0aXR1dGlvbnNaHSIbbGxveWQgZ3JvdXAgb2YgaW5zdGl0dXRpb25zkgESZW5naW5lZXJpbmdfc2Nob29s4AEA!16s%2Fg%2F11nncwjyjm?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "Plot No. 3, Knowledge Park II, Greater Noida, Uttar Pradesh 201306"
  },
  {
    id: "7",
    title: "Galgotias University",
    location: "Greater Noida",
    university: "Autonomous University",
    imgLink: "https://lh3.googleusercontent.com/d/1-Qnh6aXNjJTI_2RVG5NjR7U6NPhxvhIN",
    established: "2011",
    area: 52.0,
    naacGrade: "A+",
    description: "Galgotias University, located in Greater Noida, is a prestigious institution renowned for its commitment to academic excellence and innovation. Established under the Shakuntla Educational and Welfare Society, the university is recognized by UGC and offers a wide range of undergraduate, postgraduate, and doctoral programs across disciplines like engineering, management, law, and more. With a focus on holistic education, Galgotias University blends theoretical knowledge with practical skills to nurture future ready professionals. Spread across a sprawling campus along the Yamuna Expressway, the university provides a vibrant learning environment with state of the art infrastructure, including modern classrooms, advanced laboratories, and a well stocked library. The campus also features secure hostels, seminar halls, sports facilities, and recreational spaces, ensuring a well rounded student experience. Known for its strong placement record and industry collaborations, Galgotias University has earned recognition on national and international platforms as a hub for quality education and overall development.",
    mapLink: "https://www.google.co.in/maps/place/GALGOTIAS+COLLEGE+OF+ENGINEERING+AND+TECHNOLOGY,+Knowledge+Park+II,+Greater+Noida,+Uttar+Pradesh+201310/@28.4573114,77.4950505,17z/data=!4m7!3m6!1s0x390cc1dc8b29c0e1:0x4ee84fe65c694f0!8m2!3d28.4571329!4d77.4978!10e5!16s%2Fg%2F11b8txl6pk?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "Plot No. 2, Yamuna Expy, opposite Buddha International Circuit, Sector 17A, Greater Noida, Uttar Pradesh 203201"
  },
  {
    id: "8",
    title: "Amity University",
    location: "Greater Noida",
    university: "Autonomous University",
    imgLink: "https://lh3.googleusercontent.com/d/1Zgpi1R0jzjWQlywdZRqeSwVg40Qp8nR7",
    established: "2005",
    area: 21.0,
    naacGrade: "A+",
    description: "Amity University, located in Greater Noida, is a prestigious institution renowned for its commitment to academic excellence and innovation. Established under the Amity Education Group, the university is recognized by UGC and offers a wide range of undergraduate, postgraduate, and doctoral programs across disciplines like engineering, management, law, and more. With a focus on holistic education, Amity University blends theoretical knowledge with practical skills to nurture future ready professionals. Spread across a sprawling 21 acre campus in Knowledge Park III, the university provides a vibrant learning environment with state of the art infrastructure, including modern classrooms, advanced laboratories, and a comprehensive library. The campus also features secure hostels, seminar halls, sports facilities, and recreational spaces, ensuring a well rounded student experience. Known for its strong placement record, global collaborations, and emphasis on research, Amity University has earned recognition as a leading institution for quality education and overall development.",
    mapLink: "https://www.google.co.in/maps/place/Amity+University+Noida/@28.5439375,77.3330625,3a,75y,90t/data=!3m8!1e2!3m6!1svXfKS_gHCJxCrpd65CAwoQ!2e0!3e3!6shttps:%2F%2Flh3.googleusercontent.com%2Fgps-proxy%2FALd4DhE9ild3F7noyrdv_Qz6vHlrXXdiySDvtu4WYjUZ8zsAHQozoHtwHjJqQyyrl9DgoCf4_2uQ2fyXxKiY3Gq5YkgXwrZdogZ1UjHepqhdbZRr63ik_QN-0H_J7DqsquPNbwE72-8UudxJbHLQTVhZ-2klxvtfTlONbgor26Gf7wfIEgVlfnvh9XT9mpeuv2gBKwXjlg%3Dw129-h86-k-no!7i1280!8i853!4m7!3m6!1s0x390ce44e80a9461b:0x302ec8d3d5cb8d1a!8m2!3d28.5439375!4d77.3330625!10e5!16zL20vMDhqYjZf?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "Amity Rd, Sector 125, Noida, Uttar Pradesh 201301"
  },
  {
    id: "9",
    title: "ITS Engineering College",
    location: "Greater Noida",
    university: "AKTU Lucknow",
    imgLink: "https://lh3.googleusercontent.com/d/17TraBZPXHnIMqMpVLHZIDcmPNv2PA6xe",
    established: "2006",
    area: 10.0,
    naacGrade: NaN,
    description: "ITS Engineering College, located in Greater Noida, is a distinguished institution dedicated to providing high quality technical and management education. Established in 2006 under the ITS Education Group, the college is affiliated with Dr. A.P.J. Abdul Kalam Technical University and approved by AICTE. Known for its industry focused curriculum and innovative teaching methods, ITS Engineering College offers programs like B.Tech and MBA, fostering both academic and professional excellence. Spread across a modern campus in Knowledge Park III, the college provides a vibrant learning environment with state of the art infrastructure, including advanced classrooms, well equipped labs, and a comprehensive library. The campus also features secure hostels, seminar halls, sports facilities, and recreational spaces, ensuring a holistic student experience. With a strong emphasis on placements, skill development, and entrepreneurship, ITS Engineering College has earned recognition as one of the top institutions in the region, shaping future ready professionals and leaders.",
    mapLink: "https://www.google.co.in/maps/place/ITS+Engineering+College/@28.4692269,77.4893724,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipM6URrVywVyT_AYi-gOjlXCWQlowqDweCnlELDj!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipM6URrVywVyT_AYi-gOjlXCWQlowqDweCnlELDj%3Dw128-h86-k-no!7i1024!8i683!4m7!3m6!1s0x390cea0bb627ba3f:0x98ceba75b8e54979!8m2!3d28.4686536!4d77.4886966!10e5!16s%2Fm%2F0ch3984?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "46, Knowledge Park III, Greater Noida, Uttar Pradesh 201310"
  },
  {
    id: "10",
    title: "Noida International University",
    location: "Greater Noida",
    university: "Autonomous University",
    imgLink: "https://lh3.googleusercontent.com/d/1HJxKhhiNLMtZGNbV8Hxr3Vr1kFhzHTuB",
    established: "2010",
    area: 75.0,
    naacGrade: "A+",
    description: "Noida International University (NIU), located in Greater Noida, is a prominent institution dedicated to providing world class education across diverse fields such as engineering, management, law, and health sciences. Established in 2010 under the Maruti Educational Trust, NIU is recognized by UGC and offers a wide range of undergraduate, postgraduate, and doctoral programs. The university is known for its innovative teaching methods, industry aligned curriculum, and emphasis on research and skill development. Spread across a sprawling 75 acre campus along the Yamuna Expressway, NIU provides a vibrant learning environment with state of the art infrastructure, including modern classrooms, advanced laboratories, and a well stocked library. The campus also features secure hostels, seminar halls, sports facilities, and recreational spaces, ensuring a holistic student experience. With a strong focus on placements, global collaborations, and fostering innovation, NIU has earned recognition as a leading institution for quality education and overall development.",
    mapLink: "https://www.google.co.in/maps/place/Noida+International+University/@28.3720633,77.5405955,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipP6a5jnH7uGJZ6gvYSoVNXBFdOBBUoWIAY0DB_q!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipP6a5jnH7uGJZ6gvYSoVNXBFdOBBUoWIAY0DB_q%3Dw152-h86-k-no!7i1920!8i1080!4m7!3m6!1s0x390cc74a1da523db:0xf0736e7a99d63eb0!8m2!3d28.3722793!4d77.5394911!10e5!16s%2Fm%2F0bs8kqk?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "Plot 1, Yamuna Expy, Sector 17A, Uttar Pradesh 203201"
  },
  {
    id: "11",
    title: "JIMS Engineering Management Technical Campus",
    location: "Greater Noida",
    university: "GGSIPU Delhi",
    imgLink: "https://lh3.googleusercontent.com/d/1bHQPDy0JosfzxeiUBrjOKaofQkACWMyG",
    established: "2008",
    area: 5.5,
    naacGrade: NaN,
    description: "JIMS Engineering Management Technical Campus (JEMTEC), Greater Noida Situated in the vibrant Knowledge Park of Greater Noida, JEMTEC is a premier institution under the Jagan Nath Gupta Memorial Educational Society. Established in 2011, it is affiliated with Guru Gobind Singh Indraprastha University and approved by AICTE. JEMTEC offers a diverse range of programs, including B.Tech, BBA, BCA, Law, and B.Ed, blending academic rigor with practical exposure. The campus boasts modern infrastructure, well equipped labs, spacious classrooms, and recreational facilities, fostering a holistic learning environment. With a dedicated placement cell and strong industry connections, JEMTEC ensures students are career ready. Its emphasis on innovation, extracurricular activities, and personality development makes it a standout choice for aspiring professionals. JEMTEC is more than an institution , it's a launchpad for success.",
    mapLink: "https://www.google.co.in/maps/place/JIMS+Engineering+Management+Technical+Campus+(JEMTEC)/@28.4658921,77.4830007,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipM8HIjInHniRElkaijoEwcCnYtp1lv5jgA-QYzI!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipM8HIjInHniRElkaijoEwcCnYtp1lv5jgA-QYzI%3Dw86-h114-k-no!7i3456!8i4608!4m7!3m6!1s0x390cea0f70009f75:0x22c86d7a6f81b56b!8m2!3d28.465885!4d77.4830103!10e5!16s%2Fg%2F12ht1yf56?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "48/4, Knowledge Park III, Greater Noida, Noida, Uttar Pradesh 201303"
  },
  {
    id: "12",
    title: "Greater Noida Institute of Technology (GNIT)",
    location: "Greater Noida",
    university: "AKTU Lucknow",
    imgLink: "https://lh3.googleusercontent.com/d/14LlDNkioatUzHEV6cMUpjRtB-IjP7KVk",
    established: "2001",
    area: 2.0,
    naacGrade: "A+",
    description: "Greater Noida Institute of Technology (GNIOT), Greater Noida Established in 2001, GNIOT is a leading institution in the Delhi NCR region, affiliated with Dr. A.P.J. Abdul Kalam Technical University and approved by AICTE. Known for its commitment to academic excellence, GNIOT offers a wide range of programs, including B.Tech, MBA, and MCA, designed to equip students with both theoretical knowledge and practical skills. The sprawling campus features state of the art infrastructure, modern labs, and vibrant recreational spaces, fostering a dynamic learning environment. With a strong focus on placements, GNIOT has built robust industry connections, ensuring students are career ready. The institute also emphasizes extracurricular activities and personality development, nurturing well-rounded professionals. GNIOT stands as a beacon of quality education and holistic growth in the heart of Greater Noida.",
    mapLink: "https://www.google.co.in/maps/place/GNIT+IPU+campus/@28.4589101,77.495491,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipPrCHdY4HZYmzbDWp5F6anxUZVQ5IqM6FYdYxHr!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipPrCHdY4HZYmzbDWp5F6anxUZVQ5IqM6FYdYxHr%3Dw129-h86-k-no!7i3571!8i2376!4m7!3m6!1s0x390cc134d792ae35:0x5f7bc175bf3517c!8m2!3d28.4589101!4d77.495491!10e5!16s%2Fg%2F11fcmlm79x?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "Plot No. 7, Knowledge Park II, Greater Noida, Uttar Pradesh 201310"
  },
  {
    id: "13",
    title: "GNIOT Institute of Management Studies (GIMS)",
    location: "Greater Noida",
    university: "AKTU Lucknow",
    imgLink: "https://lh3.googleusercontent.com/d/1cRqcV2xCs__pOp8YZI2yleCvBEafxkXx",
    established: "2020",
    area: 25.0,
    naacGrade: "A+",
    description: "GNIOT Institute of Management Studies (GIMS), Greater Noida , A part of the prestigious GNIOT Group, GIMS is a leading business school in the Delhi NCR region, offering an AICTE approved PGDM program. Known for its industry focused curriculum and dual specialization options, GIMS equips students with the skills needed for today\u2019s competitive business world. The institute emphasizes experiential learning, global exposure, and innovation, fostering well rounded professionals. Located in the futuristic township of Greater Noida, the campus provides state of the art facilities, including modern classrooms, advanced labs, and vibrant recreational spaces. With strong industry ties and a dedicated placement cell, GIMS ensures excellent career opportunities for its students. It\u2019s more than just an institution , it\u2019s a launchpad for aspiring leaders and entrepreneurs.",
    mapLink: "https://www.google.co.in/maps/place/Greater+Noida+Institute+of+Management+(GNIM)/@28.4590927,77.4956589,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipOv183r5IIzOK6anw0XVR4B62R1RCWRS6m73BGc!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipOv183r5IIzOK6anw0XVR4B62R1RCWRS6m73BGc%3Dw129-h86-k-no!7i6000!8i4000!4m7!3m6!1s0x390cc10038d6df2d:0x4cc1373d1832d6a1!8m2!3d28.4589656!4d77.4954861!10e5!16s%2Fg%2F11vyqkqg_b?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "Plot No. Seven, Knowledge Park II, Greater Noida, Uttar Pradesh 201310"
  },
  {
    id: "14",
    title: "IILM University",
    location: "Greater Noida",
    university: "Autonomous University",
    imgLink: "https://lh3.googleusercontent.com/d/1dPIYoWWK85Gwjk1NBVE1LGab_vi5fM-z",
    established: "2004",
    area: 26.0,
    naacGrade: "A ",
    description: "IILM University, Greater Noida Established under the Uttar Pradesh Private University Act, IILM University is a hub of innovation and excellence in the Delhi NCR region. Located in Knowledge Park II, Greater Noida, the university spans a sprawling 26 acre campus equipped with state of the art facilities. With a focus on global, inclusive, and responsible education, IILM offers diverse programs in fields like engineering, management, liberal arts, and law. The university emphasizes experiential learning, research, and industry collaboration, preparing students for dynamic careers. Its vibrant campus life, dedicated faculty, and strong alumni network create a nurturing environment for holistic growth. IILM University is more than an academic institution , it\u2019s a place where future leaders and innovators are shaped.",
    mapLink: "https://www.google.co.in/maps/place/IILM+University,+Greater+Noida/@28.4601766,77.4916709,3a,101.8y,90t/data=!3m8!1e2!3m6!1sAF1QipNJzUOWbXFjEP-xS1uq7ITdKq1scE0cD0kojMcz!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipNJzUOWbXFjEP-xS1uq7ITdKq1scE0cD0kojMcz%3Dw142-h86-k-no!7i665!8i400!4m7!3m6!1s0x390cc1e13dcbf0eb:0xfcf1c4d9749a78b4!8m2!3d28.4603517!4d77.4913143!10e5!16s%2Fm%2F07k6cg0?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "Plot No.18, Iilm College Of Engineering & Technology, 16, Knowledge Park II, Greater Noida, Uttar Pradesh 201306"
  },
  {
    id: "15",
    title: "IIMT Group of Colleges",
    location: "Greater Noida",
    university: "AKTU Lucknow",
    imgLink: "https://lh3.googleusercontent.com/d/1UOQi3fGw7Jmd30A20JEtUJKCtAvZ3Rwv",
    established: "1994",
    area: 13.3,
    naacGrade: "B++",
    description: "IIMT Group of Colleges, Greater Noida Established in 1994, IIMT Group of Colleges is a renowned educational institution in the Delhi NCR region, offering a wide array of programs in engineering, management, law, pharmacy, and more. Affiliated with Dr. A.P.J. Abdul Kalam Technical University and approved by AICTE, IIMT is committed to academic excellence and holistic development. The sprawling campus features modern infrastructure, well equipped labs, and vibrant recreational spaces, creating an ideal learning environment. With a strong focus on placements, IIMT has built robust industry connections, ensuring excellent career opportunities for its students. The institution also emphasizes extracurricular activities, innovation, and personality development, nurturing well rounded professionals. IIMT Group of Colleges stands as a beacon of quality education, empowering students to achieve their dreams and make a mark in their chosen fields.",
    mapLink: "https://www.google.co.in/maps/place/IIMT+Groups+of+Colleges/@28.4813038,77.4929422,3a,75y,90t/data=!3m8!1e2!3m6!1sCIHM0ogKEICAgIDX8fCmPw!2e10!3e12!6shttps:%2F%2Flh3.googleusercontent.com%2Fgps-cs-s%2FAB5caB_ROhmTjHIqoh7WPzQgYXRUvwXkdAeKUxB-Hj0v_ScZwG31wk7ljNwIAECE-8_d_lQ9uw6LI7d_VbtqiHif3mZXC-7uAc-CcDTwbOlvgk8HjzxHyRBsthK5T-VhCx79LVN_p6Bp%3Dw203-h270-k-no!7i3024!8i4032!4m7!3m6!1s0x390ceb9597620805:0xbca33089d0aae140!8m2!3d28.4812608!4d77.4928633!10e5!16s%2Fg%2F11ks8rmxbv?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "FFJR+RVP IIMT COLLEGE OF MANAGEMENT, Knowledge Park III, Greater Noida, Namauli, Uttar Pradesh 201310"
  },
  {
    id: "16",
    title: "Sharda University",
    location: "Greater Noida",
    university: "Autonomous University",
    imgLink: "https://lh3.googleusercontent.com/d/13h8zwymepRxjV4alUTmqedZ3CLyOqU1M",
    established: "2009",
    area: 63.0,
    naacGrade: "A+",
    description: "Sharda University, Greater Noida Established in 2009, Sharda University is a premier private institution in the Delhi NCR region, recognized by the UGC. Spread across a sprawling 63 acre campus, it offers over 135 programs in diverse fields such as engineering, management, law, medicine, and more. Known for its global outlook, the university hosts students from 95+ countries, fostering a multicultural learning environment. With state of the art infrastructure, including modern labs, libraries, and recreational facilities, Sharda ensures holistic development. The university emphasizes innovation, research, and industry collaboration, preparing students for dynamic careers. Its vibrant campus life, dedicated faculty, and strong placement record make Sharda University a hub of opportunities and excellence. It\u2019s more than just an institution , it\u2019s a gateway to a world class education and a bright future.",
    mapLink: "https://www.google.co.in/maps/place/Sharda+University/@28.4730987,77.482967,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipNoLZLn51qSXU89UKr_-AtXl0ib0q6uAIF2V7wZ!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipNoLZLn51qSXU89UKr_-AtXl0ib0q6uAIF2V7wZ%3Dw107-h86-k-no!7i1080!8i866!4m7!3m6!1s0x390cea0f7b91511b:0x486f13bd49e5e7ae!8m2!3d28.4730668!4d77.48291!10e5!16s%2Fm%2F0bwl_4c?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "plot no 32, 34, Knowledge Park III, Greater Noida, Uttar Pradesh 201310"
  },
  {
    id: "17",
    title: "Mangalmay Group of Institutiions",
    location: "Greater Noida",
    university: "AKTU Lucknow",
    imgLink: "https://lh3.googleusercontent.com/d/1tHYdJmfoKClfaOmZPeu5U6NDQtUMhkoQ",
    established: "2002",
    area: 10.0,
    naacGrade: "A",
    description: "Mangalmay Group of Institutions, Greater Noida Established in 2002, Mangalmay Group of Institutions is a NAAC accredited institution dedicated to fostering innovation and excellence. Affiliated with Dr. A.P.J. Abdul Kalam Technical University and approved by AICTE, it offers a wide range of programs in management, engineering, biotechnology, commerce, and education. The campus, located in Knowledge Park II, Greater Noida, provides a vibrant learning environment with modern infrastructure, well equipped labs, and recreational facilities. Mangalmay emphasizes holistic development, blending academic rigor with extracurricular activities and personality enhancement programs. With a strong focus on placements and industry collaboration, the institution ensures students are well prepared for their careers. Mangalmay Group of Institutions is more than just an academic hub , it\u2019s a nurturing ground for future leaders and innovators.",
    mapLink: "https://www.google.co.in/maps/place/Mangalmay+Group+Of+Institutions/@28.4590645,77.4943051,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipM1O5pOCEv28z4Av0UuG4WK-eQfz3WK98sM9Z4j!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipM1O5pOCEv28z4Av0UuG4WK-eQfz3WK98sM9Z4j%3Dw152-h86-k-no!7i1080!8i608!4m7!3m6!1s0x390ce97aaaaaaaad:0xe61b7707fa7b3b2b!8m2!3d28.4590508!4d77.4943141!10e5!16s%2Fg%2F11b6q55jdh?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "Plot No. 8 & 9, BIMTECH Rd, Knowledge Park II, Greater Noida, Uttar Pradesh 201310"
  },
  {
    id: "18",
    title: "Accurate Group of Institutiions",
    location: "Greater Noida",
    university: "AKTU Lucknow",
    imgLink: "https://lh3.googleusercontent.com/d/18LQ9gy4JvUaMr0tJwe_m6z_-wrBcFoPA",
    established: "2006",
    area: 16.0,
    naacGrade: NaN,
    description: "Accurate Group of Institutions, Greater Noida Established in 2006, Accurate Group of Institutions is a prominent educational hub in the Delhi NCR region, offering a wide range of programs in engineering, management, architecture, and more. Affiliated with Dr. A.P.J. Abdul Kalam Technical University and approved by AICTE, the institution is known for its academic excellence and industry focused curriculum. The 16 acre lush green campus provides a serene yet dynamic learning environment, featuring modern classrooms, advanced labs, and vibrant recreational spaces. Accurate emphasizes holistic development through experiential learning, innovation, and extracurricular activities. With strong industry connections and a dedicated placement cell, the institution ensures excellent career opportunities for its students. Accurate Group of Institutions is more than just an academic center , it\u2019s a launchpad for aspiring professionals and future leaders.",
    mapLink: "https://www.google.co.in/maps/place/Accurate+Group+of+Institutions/@28.4640504,77.4863032,3a,82.8y,90t/data=!3m8!1e2!3m6!1sAF1QipOE5mbHAGk8qtC3N1qscewYEWok1naQSRo16Gty!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipOE5mbHAGk8qtC3N1qscewYEWok1naQSRo16Gty%3Dw151-h86-k-no!7i928!8i528!4m7!3m6!1s0x390cc1cf4330d909:0xd1a0629dadf396d2!8m2!3d28.4639187!4d77.4864253!10e5!16s%2Fg%2F11p5gb9wyt?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "Plot No 49, Knowledge Park III, Greater Noida, Uttar Pradesh 201304"
  },
  {
    id: "19",
    title: "I-Business institute (IBI)",
    location: "Greater Noida",
    university: "Autonomous PGDM",
    imgLink: "https://lh3.googleusercontent.com/d/1J__Yi-yWkt_sRGnFXi2EG9Dc6hdBuPwg",
    established: "2008",
    area: 5.0,
    naacGrade: NaN,
    description: "I-Business Institute (IBI), Greater Noida Located in Knowledge Park II, Greater Noida, I-Business Institute is a distinguished management school offering an AICTE approved PGDM program. Established in 2008, IBI is known for its industry focused curriculum, dual specializations, and emphasis on experiential learning. The institute provides global exposure through international partnerships and programs, preparing students for the demands of a dynamic business world. The campus features modern infrastructure, including advanced classrooms, labs, and recreational spaces, fostering a vibrant learning environment. With a dedicated placement cell and strong industry connections, IBI ensures excellent career opportunities for its students. IBI is more than just an academic institution , it\u2019s a nurturing ground for future leaders and innovators, blending academic excellence with practical insights to shape successful professionals.",
    mapLink: "https://www.google.co.in/maps/place/I+Business+Institute/@28.4756448,77.4955572,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipMMWAtip4VbOcQ4NoFDIaYvfXdX9vxedk4F98s_!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipMMWAtip4VbOcQ4NoFDIaYvfXdX9vxedk4F98s_%3Dw129-h86-k-no!7i6720!8i4480!4m7!3m6!1s0x390cea72f05a1a09:0xe593837197a4cd3a!8m2!3d28.4755348!4d77.4952591!10e5!16s%2Fg%2F1tgdrj0v?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "Plot No.: 35, Knowledge Park II, Greater Noida, Uttar Pradesh 201310"
  },
  {
    id: "20",
    title: "Dronacharya Group of Institutiions (DGI)",
    location: "Greater Noida",
    university: "AKTU Lucknow",
    imgLink: "https://lh3.googleusercontent.com/d/1nWG2YdBLs8WZxXojHAtbfSXgiBSjQbUQ",
    established: "2006",
    area: 10.0,
    naacGrade: "B++",
    description: "Dronacharya Group of Institutions (DGI), Greater Noida Established in 2006, DGI is a leading institution in the Delhi NCR region, affiliated with Dr. A.P.J. Abdul Kalam Technical University and approved by AICTE. Known for its commitment to academic and professional excellence, DGI offers a range of B.Tech and MBA programs, fostering innovation and technical expertise. The campus, located in Knowledge Park III, features modern infrastructure, advanced labs, and vibrant recreational spaces, creating an ideal environment for learning and growth. With a strong focus on placements, DGI has built robust industry connections, ensuring excellent career opportunities for its students. The institution also emphasizes research, extracurricular activities, and personality development, nurturing well rounded professionals. DGI is more than just an academic institution , it\u2019s a launchpad for aspiring engineers and leaders, dedicated to shaping a brighter future.",
    mapLink: "https://www.google.co.in/maps/place/Dronacharya+Group+of+Institutions/@28.4763192,77.4785231,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipMmdQKjOJc7OBcbygw8RFm4JLY9G18aCeRNpImw!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipMmdQKjOJc7OBcbygw8RFm4JLY9G18aCeRNpImw%3Dw152-h86-k-no!7i3822!8i2150!4m7!3m6!1s0x390cea052e4af691:0x16e3e3e82a7dbd8a!8m2!3d28.476137!4d77.4787361!10e5!16s%2Fg%2F11c74yqgmm?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "B-27, APJ Abdul Kalam Rd, Knowledge Park III, Greater Noida, Uttar Pradesh 201306"
  },
  {
    id: "21",
    title: "Bennett University",
    location: "Greater Noida",
    university: "Autonomous University",
    imgLink: "https://lh3.googleusercontent.com/d/1kq895aFUEsuYk7ypJ_CFQ6JHytSSjyDA",
    established: "2016",
    area: 68.0,
    naacGrade: "A+",
    description: "Bennett University, Greater Noida Established in 2016 by The Times Group, Bennett University is a modern, research driven institution in the Delhi NCR region. Spread across a sprawling campus in Greater Noida, it offers cutting edge programs in engineering, management, law, media, and liberal arts. The university emphasizes experiential learning, global exposure, and innovation, preparing students for dynamic careers. With state of the art infrastructure, including advanced labs, a vibrant sports complex, and skill enhancing clubs, Bennett fosters holistic development. Its strong industry connections, backed by The Times Group, ensure excellent placement opportunities. Bennett University is more than just an academic institution , it\u2019s a launchpad for future leaders and innovators, blending academic rigor with practical insights to shape successful professionals.",
    mapLink: "https://www.google.co.in/maps/place/Bennett+University/@28.45066,77.5842238,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipOodC1fqGFUAse3Ei859rdSdc2Oy1xQb2SmkaOy!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipOodC1fqGFUAse3Ei859rdSdc2Oy1xQb2SmkaOy%3Dw120-h86-k-no!7i2048!8i1464!4m7!3m6!1s0x390cbf94deb6bc39:0x7ba6bedc9a2b537f!8m2!3d28.4506465!4d77.5841978!10e5!16s%2Fg%2F11c3wvm4q_?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "Plot Nos 8, 11, TechZone 2, Greater Noida, Uttar Pradesh 201310"
  },
  {
    id: "22",
    title: "United Group of Institutiions",
    location: "Greater Noida",
    university: "AKTU Lucknow",
    imgLink: "https://lh3.googleusercontent.com/d/1U6nWfP9zbT9tl5bf-UARrnnMBvfKGphp",
    established: "2005",
    area: 20.0,
    naacGrade: NaN,
    description: "United Group of Institutions (UGI), Greater Noida Founded in 2005, United Group of Institutions is a distinguished name in technical and management education, affiliated with Dr. A.P.J. Abdul Kalam Technical University and approved by AICTE. The institution offers a wide range of programs, including B.Tech, MBA, and pharmacy, with a focus on academic excellence and practical learning. Spread across a sprawling campus, UGI boasts state of the art infrastructure, modern labs, and vibrant recreational spaces, creating an ideal environment for holistic development. With a strong emphasis on placements, UGI has forged robust industry connections, ensuring excellent career opportunities for its students. The institution also nurtures innovation, extracurricular activities, and personality development, shaping well rounded professionals. United Group of Institutions is more than just an academic hub , it\u2019s a gateway to success and a brighter future.",
    mapLink: "https://www.google.co.in/maps/place/United+Group+of+Institutions/@28.4650261,77.4888424,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipMGXIW9oLC6nITQlJasAEOKXE3ROehK8lTG_mku!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipMGXIW9oLC6nITQlJasAEOKXE3ROehK8lTG_mku%3Dw86-h114-k-no!7i3456!8i4608!4m7!3m6!1s0x8eb4bbeedf2cf8f7:0xd8a33afffd7812e7!8m2!3d28.4649451!4d77.4889022!10e5!16s%2Fg%2F11lc_jzhdh?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "50, Knowledge Park III, Greater Noida, Uttar Pradesh 201310"
  },
  {
    id: "23",
    title: "Birla Institute of Management Technology (BIMTECH)",
    location: "Greater Noida",
    university: "Autonomous PGDM",
    imgLink: "https://lh3.googleusercontent.com/d/1VN-hXFBhxe03PN8Xr87gB9aRY8c-J_h4",
    established: "1988",
    area: 7.0,
    naacGrade: "A+",
    description: "Birla Institute of Management Technology (BIMTECH), Greater Noida Established in 1988 under the aegis of the Birla Academy of Art and Culture, BIMTECH is a premier business school in the Delhi NCR region. Accredited by AACSB, it offers AICTE approved PGDM programs with specializations in marketing, finance, operations, and more. The lush green campus in Knowledge Park II provides a serene yet dynamic learning environment, featuring modern infrastructure, advanced labs, and vibrant recreational spaces. BIMTECH emphasizes experiential learning, global exposure, and ethical leadership, preparing students for the challenges of the corporate world. With a strong alumni network, industry connections, and a dedicated placement cell, the institute ensures excellent career opportunities. BIMTECH is more than just an academic institution , it\u2019s a nurturing ground for future leaders and innovators, blending academic rigor with practical insights to shape successful professionals.",
    mapLink: "https://www.google.co.in/maps/place/BIMTECH+-+Birla+Institute+of+Management+Technology/@28.4585643,77.4936454,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipNNhWooow6llZUgDqj6uGMlRFSIpXxHZ1rWhcCl!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipNNhWooow6llZUgDqj6uGMlRFSIpXxHZ1rWhcCl%3Dw153-h86-k-no!7i2714!8i1523!4m7!3m6!1s0x390cc1ddbcb1ef8b:0xf6fc0a3d2855d53c!8m2!3d28.459171!4d77.4945391!10e5!16zL20vMDltMnhy?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "Knowledge Park 2, NCR, Plot Number 5, BIMTECH Rd, Greater Noida, Uttar Pradesh 201306"
  },
  {
    id: "24",
    title: "Delhi Technical Campus (DTC)",
    location: "Greater Noida",
    university: "GGSIPU Delhi",
    imgLink: "https://lh3.googleusercontent.com/d/1HKCBc1N9sIsAHe99JfPdmWpRpLInsMYP",
    established: "2013",
    area: 5.0,
    naacGrade: "A ",
    description: "Delhi Technical Campus (DTC), Greater Noida Affiliated with Guru Gobind Singh Indraprastha University and approved by AICTE, Delhi Technical Campus is a premier institution in the Delhi NCR region. Located in Knowledge Park III, Greater Noida, DTC offers a range of programs in engineering, management, architecture, and more. The campus features state of the art infrastructure, including modern labs, spacious classrooms, and vibrant recreational spaces, fostering a dynamic learning environment. With a strong focus on innovation, research, and industry collaboration, DTC ensures students are well prepared for professional success. The institute also emphasizes extracurricular activities and holistic development, nurturing well rounded individuals. Backed by a dedicated placement cell and robust industry connections, DTC provides excellent career opportunities. It\u2019s more than just an academic institution , it\u2019s a platform for aspiring professionals to achieve their dreams and thrive in their chosen fields.",
    mapLink: "https://www.google.co.in/maps/place/Delhi+Technical+Campus/@28.4746493,77.4762282,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipMVaLwhbiBA9zRWbNMyBLBllx-1U6KYvXl_MF9B!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipMVaLwhbiBA9zRWbNMyBLBllx-1U6KYvXl_MF9B%3Dw114-h86-k-no!7i1443!8i1080!4m7!3m6!1s0x390cebdaaaaaaaab:0xef507664000ad02f!8m2!3d28.4747146!4d77.4762434!10e5!16s%2Fg%2F12m9dfp5l?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "28, FFHG+259, 1, Knowledge Park III, Greater Noida, Gujarpur, Uttar Pradesh 201306"
  },
  {
    id: "25",
    title: "Kailash Insitute of Nursing & Para-Medical Sciences",
    location: "Greater Noida",
    university: "CCSU Meerut",
    imgLink: "https://lh3.googleusercontent.com/d/1GYeOAfU_NgRmkLsMrQp1YJFp6mSuxmt5",
    established: "2004",
    area: 3.0,
    naacGrade: NaN,
    description: "Kailash Institute of Nursing and Para-Medical Sciences, Greater Noida Established in 2004, Kailash Institute of Nursing and Para-Medical Sciences is a premier institution dedicated to healthcare education. Affiliated with Chaudhary Charan Singh University, Meerut, and Atal Bihari Vajpayee Medical University, Lucknow, the institute is recognized by the Indian Nursing Council (INC). It offers a range of undergraduate and postgraduate programs in nursing, physiotherapy, and paramedical sciences. Located in Knowledge Park III, Greater Noida, the campus spans 3 acres and features modern academic blocks, well equipped labs, and in campus hostels. With a focus on practical training and holistic development, the institute prepares students for successful careers in healthcare. Kailash Institute is more than just an academic centre , it\u2019s a nurturing ground for compassionate and skilled healthcare professionals, committed to making a difference in society.",
    mapLink: "https://www.google.co.in/maps/place/Kailash+Institute+of+Nursing+and+ParaMedical+Sciences/@28.4704543,77.4881911,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipO_yg0QJu_LNAjFNMZew5tHse5K7dNi6ETbM3po!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipO_yg0QJu_LNAjFNMZew5tHse5K7dNi6ETbM3po%3Dw285-h86-k-no!7i12666!8i3822!4m7!3m6!1s0x390cea0be629ab65:0x98aa058ef900d5dc!8m2!3d28.4702398!4d77.4879045!10e5!16s%2Fg%2F124svh75p?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "46A/1, Knowledge Park III, Greater Noida, Uttar Pradesh 201310"
  },
  {
    id: "26",
    title: "Gautam Buddha University (GBU)",
    location: "Greater Noida",
    university: "Autonomous University",
    imgLink: "https://lh3.googleusercontent.com/d/1YTywhNtsVgRxWQuCWkVNg7in63aDOvAX",
    established: "2002",
    area: 511.0,
    naacGrade: "B+",
    description: "Gautam Buddha University (GBU), Greater Noida Established in 2008 under the Uttar Pradesh Gautam Buddha University Act, GBU is a state government university recognized by the UGC and accredited by NAAC with a B+ grade. Spread across a sprawling 511 acre campus adjacent to the Yamuna Expressway, the university offers undergraduate, postgraduate, and doctoral programs in engineering, management, biotechnology, Buddhist studies, and more. GBU emphasizes research, innovation, and holistic development, fostering a dynamic learning environment. The campus features modern infrastructure, including advanced labs, libraries, and recreational facilities, ensuring students thrive academically and personally. With a focus on character, creativity, and competence, GBU prepares students to excel in their chosen fields. It\u2019s more than just an institution , it\u2019s a gateway to knowledge and growth.",
    mapLink: "https://www.google.co.in/maps/place/Gautam+Buddha+University/@28.4209228,77.5267391,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipMsbtlczoWa1zzkE-b910KVn_YuW8iNG9LiPPvD!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipMsbtlczoWa1zzkE-b910KVn_YuW8iNG9LiPPvD%3Dw152-h86-k-no!7i4032!8i2268!4m7!3m6!1s0x390cc0f918abee8d:0x8c72169fdd7154b0!8m2!3d28.4209228!4d77.5267391!10e5!16s%2Fm%2F07s9cpn?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "Opp, Yamuna Expy, Greater Noida, Uttar Pradesh 201312"
  },
  {
    id: "27",
    title: "Ajay Kumar Garg Engineering College (AKGEC)",
    location: "Ghaziabad",
    university: "AKTU Lucknow",
    imgLink: "https://lh3.googleusercontent.com/d/1rzTcZoGOu_Roc-NJGB67JcHPtvG1pl8D",
    established: "1988",
    area: 40.0,
    naacGrade: "A++",
    description: "Ajay Kumar Garg Engineering College illuminates the educational landscape of Ghaziabad as a sanctuary of technical excellence and innovation. This intellectual haven, established by the forward-thinking Ajay Kumar Garg Technical Education Society, operates under Dr. A.P.J. Abdul Kalam Technical University's academic umbrella. The lush 40-acre campus breathes life into engineering education through its immersive approach where technical theories transform into practical mastery. Within its embracing boundaries, students explore multidimensional B.Tech, M.Tech, and MBA pathways guided by mentors who balance analytical rigor with creative problem-solving. The college pulsates with innovation \u2013 from sophisticated robotics laboratories to collaborative learning spaces where ideas flourish organically. AKGEC's crown jewel remains its remarkable industry integration where classroom concepts seamlessly blend with workplace realities, crafting versatile professionals who don't merely adapt to technological evolution \u2013 they drive it with vision and purpose.",
    mapLink: "https://www.google.co.in/maps/place/Ajay+Kumar+Garg+Engineering+College/@28.6756147,77.5020148,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipN64N3S_h2V147J0GWIaMXXh8-EoUh8Bvx_u4oE!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipN64N3S_h2V147J0GWIaMXXh8-EoUh8Bvx_u4oE%3Dw152-h86-k-no!7i4000!8i2250!4m7!3m6!1s0x390cf30885b1e2a5:0x9983675e24c6638b!8m2!3d28.6756736!4d77.5020041!10e5!16zL20vMGJ4aGdf?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "27th KM Milestone, Delhi - Meerut Expy, Ghaziabad, Uttar Pradesh 201015"
  },
  {
    id: "28",
    title: "ABES Engineering College (ABESEC)",
    location: "Ghaziabad",
    university: "AKTU Lucknow",
    imgLink: "https://lh3.googleusercontent.com/d/1ADZ4doy8xD4J92CKlrhAfZ9fwE8VZfty",
    established: "2000",
    area: 17.0,
    naacGrade: "A ",
    description: "Nestled in the bustling educational corridor of Ghaziabad, ABES Engineering College stands as a beacon of technical ingenuity and professional transformation. This vibrant institution, birthed by the visionary ABES Trust, operates under the academic umbrella of Dr. A.P.J. Abdul Kalam Technical University. The college's expansive NH-24 campus buzzes with intellectual energy, featuring cutting-edge laboratories where innovation thrives and digital libraries where knowledge blooms. Students immerse themselves in comprehensive B.Tech, M.Tech, and MCA programs designed to spark creativity and technical mastery. Beyond the gleaming glass facades of smart classrooms lie comfortable residential quarters and lively sports arenas that pulse with youthful enthusiasm. ABESEC doesn't merely educate; it crafts industry titans through its powerful corporate connections and rigorous skill development initiatives, launching graduates into trajectories of remarkable professional success.",
    mapLink: "https://www.google.co.in/maps/place/ABES+Engineering+College/@28.6342886,77.4459563,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipPrEkqdqvRErSgwKrhvW5-WLD_IyqBm9sB4aCOt!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipPrEkqdqvRErSgwKrhvW5-WLD_IyqBm9sB4aCOt%3Dw114-h86-k-no!7i9248!8i6936!4m7!3m6!1s0x390cee22c60837b7:0x7c35343eceb7bde0!8m2!3d28.6340537!4d77.4455928!10e5!16s%2Fm%2F0jk_wyv?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "Crossings Republik, Ghaziabad, Uttar Pradesh 201009"
  },
  {
    id: "29",
    title: "ABESIT Group of Institutions",
    location: "Ghaziabad",
    university: "AKTU Lucknow",
    imgLink: "https://lh3.googleusercontent.com/d/1pgCpcsbxJjtsw9lkLdlN6bh1svrxmIIg",
    established: "2007",
    area: 15.0,
    naacGrade: "A+ ",
    description: "In the pulsating heart of Ghaziabad, ABES Institute of Technology shines as a crucible where technical brilliance meets practical wisdom. This forward-thinking institute, crafted by the ambitious ABES Trust, flourishes under Dr. A.P.J. Abdul Kalam Technical University's guidance. Unlike conventional technical schools, ABESIT champions an experiential learning philosophy where classroom theories transform into tangible skills. The campus hums with energy as students navigate through state-of-the-art laboratories and engage in spirited debates in modern lecture theaters. Here, B.Tech and MBA aspirants find their intellectual homes in an ecosystem designed for discovery. What truly distinguishes this institute is its vibrant industry interface \u2013 a bridge connecting academic concepts with workplace realities. ABESIT doesn't simply prepare students for exams; it molds adaptable professionals who thrive in rapidly evolving industries and lead with confidence and innovation.",
    mapLink: "https://www.google.co.in/maps/place/ABESIT+GROUP+OF+INSTITUTIONS/@28.633616,77.4477166,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipPGQnRXiiZP-R270MGjRdOaEZoriKQUUlxeV3JG!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipPGQnRXiiZP-R270MGjRdOaEZoriKQUUlxeV3JG%3Dw152-h86-k-no!7i5472!8i3078!4m7!3m6!1s0x390cee3d4e3485ed:0xe0fe1689b57c7d2e!8m2!3d28.6336014!4d77.4473543!10e5!16s%2Fm%2F0121ly37?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "ABESIT Campus Road, NE 3, near Crossing Republik, Ghaziabad, Uttar Pradesh 201009"
  },
  {
    id: "30",
    title: "KIET Group of Institutions",
    location: "Ghaziabad",
    university: "AKTU Lucknow",
    imgLink: "https://lh3.googleusercontent.com/d/19CXguWNC5wbMAxJ0-lCIE0PfmZ1kDZJn",
    established: "1998",
    area: 17.0,
    naacGrade: "A+",
    description: "KIET Ghaziabad emerges from the educational landscape as an intellectual powerhouse where dreams crystallize into professional pathways. Founded by the forward-thinking Krishna Charitable Society, this verdant 16-acre sanctuary of learning breathes life into technical education through imagination and innovation. Within its embracing walls, students explore diverse academic territories spanning B.Tech, M.Tech, MBA, and MCA, guided by mentors who balance theoretical frameworks with hands-on expertise. The campus resonates with creativity \u2013 from buzzing robotics laboratories to tranquil library corners where ideas incubate. KIET's distinctive entrepreneurial ecosystem transforms curious minds into business architects, while its seamless industry partnerships open doorways to professional possibilities. Every corridor, every classroom speaks the language of growth and discovery. This isn't merely an institution; it's a transformative journey where students metamorphose into versatile professionals ready to revolutionize technological frontiers.",
    mapLink: "https://www.google.co.in/maps/place/KIET+Group+of+Institutions/@28.7531917,77.497264,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipMhdlkdV656BiZNNf4Yl7lfN212C9IlYSXaFF4A!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipMhdlkdV656BiZNNf4Yl7lfN212C9IlYSXaFF4A%3Dw86-h110-k-no!7i720!8i928!4m16!1m8!3m7!1s0x390cf47204fb9241:0xd11ed4123c7691fe!2sKIET+GROUP+OF+INSTITUTIONS,+Muradnagar,+Uttar+Pradesh+201206!3b1!8m2!3d28.7522471!4d77.4987903!16s%2Fg%2F11b8txj61f!3m6!1s0x390cf574d18f2b6f:0x4a65c0bc0122eb2f!8m2!3d28.7531817!4d77.4970664!10e5!16s%2Fg%2F1tdw1vv3?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "Muradnagar, Uttar Pradesh 201206"
  },
  {
    id: "31",
    title: "IMS Group of Institutiions",
    location: "Ghaziabad",
    university: "AKTU Lucknow",
    imgLink: "https://lh3.googleusercontent.com/d/1oGXpEpnaLrPNk3WVLnQoFxRDkEr8A9Fe",
    established: "1990",
    area: 15.0,
    naacGrade: "A",
    description: "IMS Ghaziabad rises above the ordinary as a vibrant crucible where management theories crystallize into leadership capabilities. This urban sanctuary of learning, envisioned by the pioneering IMS Society, operates under the academic stewardship of Chaudhary Charan Singh University. Unlike traditional business schools, IMS crafts a distinctive educational tapestry where classroom concepts interweave seamlessly with industry realities. The campus pulses with intellectual energy as future business leaders navigate through MBA, PGDM, and BBA programs designed to sharpen analytical acumen and decision-making prowess. Contemporary facilities \u2013 from dynamic simulation labs to comprehensive digital libraries \u2013 create an ecosystem where management philosophies transform into practical strategies. IMS's crown jewel remains its remarkable industry integration and mentorship approach, where seasoned business veterans guide students through real-world business labyrinths, crafting ethical visionaries prepared to navigate global business complexities.",
    mapLink: "https://www.google.co.in/maps/place/IMS+Group+of+Institutions/@28.7840643,78.1852439,3a,107.5y,90t/data=!3m8!1e2!3m6!1sAF1QipMIrGY902NxvprJAMVDO94QYnjml5oS2W97O9oS!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipMIrGY902NxvprJAMVDO94QYnjml5oS2W97O9oS%3Dw128-h86-k-no!7i600!8i401!4m7!3m6!1s0x390b71423198f5e5:0x4d350424d4614da6!8m2!3d28.7840643!4d78.1852439!10e5!16s%2Fg%2F11cn94rcsd?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "Bhagwanpur Khadar, Jyotiba Phule Nagar, NH-24, Jyotiba Phule Nagar, Jyotiba Phule Nagar, Uttar Pradesh 244235"
  },
  {
    id: "32",
    title: "JSS Academy of Technical Education (JSSATE)",
    location: "Noida",
    university: "AKTU Lucknow",
    imgLink: "https://lh3.googleusercontent.com/d/1ByJotDowXfTj2-1847mEHKP9qeAziKYf",
    established: "1998",
    area: 28.0,
    naacGrade: NaN,
    description: "JSS Academy of Technical Education in Noida captivates with its harmonious blend of academic rigor and practical innovation. Established by the visionary JSS Mahavidyapeetha, this intellectual sanctuary in Sector 62 transforms educational paradigms through its distinctive approach to technical learning. The campus buzzes with creative energy as students explore multidimensional B.Tech, M.Tech, and MBA pathways, guided by mentors who champion both technical excellence and human values. Cutting-edge laboratories sit alongside tranquil green spaces, creating a perfect balance for holistic development. What truly distinguishes JSS is its remarkable innovation ecosystem where abstract theories transform into tangible solutions for real-world challenges. The institute doesn't merely transfer knowledge; it cultivates an inventive mindset and technical finesse. Here, education transcends classroom boundaries as students metamorphose into conscientious technical professionals ready to pioneer societal transformation.",
    mapLink: "https://www.google.co.in/maps/place/JSS+Academy+of+Technical+Education/@28.6141105,77.3587763,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipO3E114ZD0BgulCFsUfn7Os0IdZYE8StErfzTos!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipO3E114ZD0BgulCFsUfn7Os0IdZYE8StErfzTos%3Dw114-h86-k-no!7i4096!8i3072!4m7!3m6!1s0x390ce5992452d761:0xaaa44725147c1507!8m2!3d28.6124873!4d77.3592689!10e5!16s%2Fm%2F05c14tc?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "C-20/1, C Block, Phase 2, Industrial Area, Sector 62, Noida, Uttar Pradesh 201301"
  },
  {
    id: "33",
    title: "Jaypee Institute of Information Technology (JIIT)",
    location: "Noida",
    university: "Deemed University",
    imgLink: "https://lh3.googleusercontent.com/d/1YYnwvw1P2088cmxE4M3XhF4bEh8MlEvP",
    established: "2001",
    area: 20.0,
    naacGrade: "A",
    description: "JIIT Noida stands as a magnificent intellectual citadel where technological boundaries are constantly redefined. This progressive deemed university, birthed by the visionary Jaypee Group, has transformed Sector 62 into a hub of innovation and interdisciplinary exploration. Unlike conventional institutions, JIIT crafts a multidimensional educational experience spanning engineering, management, and natural sciences across all academic tiers. The campus breathes inspiration \u2013 from advanced research laboratories buzzing with discovery to collaborative learning spaces where ideas cross-pollinate freely. Students here don't just accumulate information; they develop critical thinking muscles through immersive learning experiences. JIIT's crowning glory lies in its vibrant innovation ecosystem where entrepreneurial seeds find fertile ground. This dynamic institution transcends traditional educational models by fostering creative problem-solving approaches and global perspectives, preparing versatile professionals who don't just fit into industry paradigms \u2013 they revolutionize them.",
    mapLink: "https://www.google.co.in/maps/place/JAYPEE+INSTITUTE+OF+INFORMATION+TECHNOLOGY/@28.6311716,77.3724075,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipO1vidhsk-z8gjvXm__DoNm_L1OXoEmdkBdbOuz!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipO1vidhsk-z8gjvXm__DoNm_L1OXoEmdkBdbOuz%3Dw86-h114-k-no!7i2448!8i3264!4m7!3m6!1s0x390ce551491b3ce7:0x7335d9fcfd4d9db0!8m2!3d28.6303537!4d77.3720932!10e5!16zL20vMDlqcXJt?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "A 10, A Block, Block A, Industrial Area, Sector 62, Noida, Uttar Pradesh 201309"
  },
  {
    id: "34",
    title: "Amity University",
    location: "Noida",
    university: "Autonomous University",
    imgLink: "https://lh3.googleusercontent.com/d/1KpgbR9OH2YEQEzqtZMgv_MDL6DYeocTc",
    established: "2005",
    area: 60.0,
    naacGrade: "A+",
    description: "Amity University Noida reigns as an educational marvel where academic brilliance meets global vision. This sprawling intellectual kingdom in Sector 125, conceived by the pioneering Ritnand Balved Education Foundation, has redefined higher education through its holistic approach to learning and discovery. Unlike traditional universities, Amity orchestrates a magnificent educational symphony across engineering, management, law, humanities, and sciences. The 60-acre campus dazzles with world-class infrastructure \u2013 from cutting-edge research centers to Olympic-caliber sports facilities \u2013 creating an ecosystem where talents flourish in all dimensions. Students navigate through programs designed not just for knowledge acquisition but for character sculpting and leadership cultivation. What truly distinguishes Amity is its borderless educational philosophy, where global partnerships and entrepreneurial initiatives transform curious minds into visionary changemakers ready to address planetary challenges with innovation, compassion, and unwavering ethical conviction.",
    mapLink: "https://www.google.co.in/maps/place/Amity+University+Noida/@28.5439375,77.3330625,3a,75y,90t/data=!3m8!1e2!3m6!1svXfKS_gHCJxCrpd65CAwoQ!2e0!3e3!6shttps:%2F%2Flh3.googleusercontent.com%2Fgps-proxy%2FALd4DhE9ild3F7noyrdv_Qz6vHlrXXdiySDvtu4WYjUZ8zsAHQozoHtwHjJqQyyrl9DgoCf4_2uQ2fyXxKiY3Gq5YkgXwrZdogZ1UjHepqhdbZRr63ik_QN-0H_J7DqsquPNbwE72-8UudxJbHLQTVhZ-2klxvtfTlONbgor26Gf7wfIEgVlfnvh9XT9mpeuv2gBKwXjlg%3Dw129-h86-k-no!7i1280!8i853!4m7!3m6!1s0x390ce44e80a9461b:0x302ec8d3d5cb8d1a!8m2!3d28.5439375!4d77.3330625!10e5!16zL20vMDhqYjZf?entry=ttu&g_ep=EgoyMDI1MDMxNy4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D#",
    address: "Amity Rd, Sector 125, Noida, Uttar Pradesh 201301"
  }
];

export default colleges;